server {

    server_name _;
    listen 80;

    location / {
        uwsgi_pass warp-demo-wsgi:8000;
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        uwsgi_param HTTP_X_FORWARDED_PROTO $scheme;
        uwsgi_param HTTP_X_FORWARDED_HOST $http_host;
        uwsgi_param HTTP_X_FORWARDED_PORT $server_port;
        uwsgi_param HTTP_X_FORWARDED_PREFIX $http_x_forwarded_prefix;
    }
}
