DROP MATERIALIZED VIEW IF EXISTS user_to_zone_roles;
DROP TABLE IF EXISTS seat_assign;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS seat;
DROP TABLE IF EXISTS zone_assign;
DROP TABLE IF EXISTS zone;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS blobs;

DROP FUNCTION IF EXISTS update_user_to_zone_roles;
DROP FUNCTION IF EXISTS set_book_zone_group;
DROP FUNCTION IF EXISTS sync_book_zone_group_from_zone;

DROP TABLE IF EXISTS db_initialized;
