http:
  routers:
    warp:
      rule: PathPrefix(`/warp`)
      entryPoints:
        - web
      service: warp
      middlewares:
        - warp-strip

  middlewares:
    warp-strip:
      stripPrefix:
        prefixes:
          - /warp

  services:
    warp:
      loadBalancer:
        servers:
          - url: http://warp-demo-nginx
